theme: jekyll-theme-minimal
title: Jakub Paszulewicz
description: Welcome to Paszul's Page (I'm a PhD in spe)
description: google scholar: https://scholar.google.com/citations?user=KyWsCS8AAAAJ&hl=en
